services:
  jenkins:
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: host   

  qemu-openbmc:  
    build:
      context: ./docker/qemu     
      dockerfile: Dockerfile
    container_name: qemu-openbmc
    network_mode: host           
    restart: "no"

volumes:
  jenkins_home:
